FROM node:18.20.0-alpine as build

WORKDIR /var/www/
RUN apk add --no-cache git

COPY package.json yarn.lock ./
RUN yarn install

COPY . .

ENV NUXT_ENV production
RUN yarn build

FROM node:18.17.0-alpine
WORKDIR /var/www/

COPY --from=build /var/www/ .

ENV HOST 0.0.0.0
ENV NUXT_ENV production

EXPOSE 3000
CMD ["yarn", "start"]
